import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="bg-slate-900 text-slate-400 py-6 mt-12 shadow-inner-top">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 text-center">
        <p className="text-sm">
          &copy; {new Date().getFullYear()} Alchemia.
        </p>
         <p className="text-xs mt-1">
          Developed by Alan Cyril Sunny.
        </p>
        <p className="text-xs mt-1">
          Disclaimer: Predictions are for informational purposes and generated by AI. Always verify critical information.
        </p>
      </div>
    </footer>
  );
};
export default Footer;